repos:
  - repo: local
    hooks:
      - id: email
        name: email
        entry: poetry run precommit-hooks check-email
        language: python
        types: [python]
        stages: [ manual ]

      - id: codestyle
        name: codestyle
        entry: poetry run precommit-hooks check-codestyle
        language: system
        types: [python]
        stages: [ manual ]

      - id: codestyle-fix
        name: codestyle-fix
        entry: poetry run precommit-hooks check-codestyle
        language: system
        types: [python]
        args: [--fix]
        stages: [manual]
