repos:
  - repo: local
    hooks:
      - id: email
        name: email
        entry: poetry run precommit-hooks check-email
        language: python
        types: [python]
        pass_filenames: false
        args: ["--allowed-domain", "yandex.ru"]

      - id: branch
        name: branch
        entry: poetry run precommit-hooks check-branch
        language: python
        types: [python]
        pass_filenames: false
        args: ["--allow-main"]

      - id: codestyle
        name: codestyle
        entry: poetry run precommit-hooks check-codestyle
        language: python
        types: [python]

      - id: codestyle-fix
        name: codestyle-fix
        entry: poetry run precommit-hooks check-codestyle
        language: python
        types: [python]
        args: [--fix]
        stages: [ manual ]

      - id: tests
        name: tests
        entry: poetry run precommit-hooks run-tests
        language: python
        types: [python]
        pass_filenames: false
        args: ["poetry", "run", "pytest"]